version: '3.8'
services:
  arma3:
    build: .
    image: lachlanstevens/arma3-server:1.1.0
    platform: linux/amd64
    container_name: arma3
    network_mode: host
    volumes:
      - './missions:/arma3/mpmissions'
      - './configs:/arma3/configs'
      - './mods:/arma3/mods'
      - './servermods:/arma3/servermods'
    env_file: .env
    restart: unless-stopped
